<?php

namespace AdventureTech\ORM\Tests\TestClasses\Entities;

use AdventureTech\ORM\Mapping\Columns\Column;
use AdventureTech\ORM\Mapping\Entity;
use AdventureTech\ORM\Mapping\Id;

#[Entity(table: 'es_accounts')]
class Account
{
    #[Id(autogenerated: false)]
    #[Column]
    public string $uuid;

    #[Column]
    public string $name;

    #[Column]
    public int $amount;
}
