<?php

namespace AdventureTech\ORM\Tests\TestClasses\Entities;

use AdventureTech\ORM\Mapping\Columns\Column;
use AdventureTech\ORM\Mapping\Entity;
use AdventureTech\ORM\Mapping\Id;

#[Entity]
class Note
{
    #[Id(autogenerated: true, useUlid: true)]
    #[Column]
    public string $id;

    #[Column]
    public string $text;
}