<?php

namespace AdventureTech\ORM\Mapping;

use Attribute;

#[Attribute(Attribute::TARGET_PROPERTY)]
readonly class Id
{
    public function __construct(public bool $autogenerated = true, public bool $useUlid = false)
    {
    }
}
