<?php

use AdventureTech\ORM\Exceptions\PersistenceException;
use AdventureTech\ORM\Persistence\PersistenceManager;
use AdventureTech\ORM\Tests\TestCase;
use AdventureTech\ORM\Tests\TestClasses\BackedEnum;
use AdventureTech\ORM\Tests\TestClasses\Entities\Post;
use AdventureTech\ORM\Tests\TestClasses\Entities\User;
use AdventureTech\ORM\Tests\TestClasses\Persistence\PostPersistence;
use AdventureTech\ORM\Tests\TestClasses\Persistence\UserPersistence;
use Carbon\CarbonImmutable;
use Illuminate\Support\Facades\DB;

test('Cannot use base persistence manager to insert entities', function () {
    $user = new User();
    expect(fn() => PersistenceManager::insert($user))->toThrow(
        Error::class,
        'Cannot call abstract method AdventureTech\ORM\Persistence\PersistenceManager::getEntityClassName()'
    );
});

test('Cannot insert non-matching entity', function () {
    $user = new User();
    expect(fn() => PostPersistence::insert($user))->toThrow(
        PersistenceException::class,
        'Cannot insert entity of type "AdventureTech\ORM\Tests\TestClasses\Entities\User" with persistence manager configured for entities of type "AdventureTech\ORM\Tests\TestClasses\Entities\Post".'
    );
});

test('Can insert entity', function () {
    $user = new User();
    $user->name = 'Name';
    UserPersistence::insert($user);
    expect(DB::table('users')->get())
        ->toHaveCount(1)
        ->first()->name->toBe('Name');
});

test('When inserting entity the id is set on the object', function () {
    $user = new User();
    $user->name = 'Name';
    UserPersistence::insert($user);
    expect($user->getIdentifier())->toBeNumeric();
});

test('Trying to insert entity with ID already set leads exception', function () {
    $user = new User();
    $user->setIdentifier(1);
    $user->name = 'Name';
    expect(fn() => UserPersistence::insert($user))->toThrow(
        PersistenceException::class,
        'Must not set autogenerated ID column when inserting entities.'
    );
});

test('Trying to insert entity with missing column leads exception', function () {
    $user = new User();
    expect(fn() => UserPersistence::insert($user))->toThrow(
        PersistenceException::class,
        'Must set non-nullable property "name".'
    );
});

test('Managed columns cannot be overridden', function () {
    $user = new User();
    $user->name = 'Name';
    $user->createdAt = CarbonImmutable::parse('2023-01-01 12:00');
    $user->updatedAt = null;
    UserPersistence::insert($user);
    expect(DB::table('users')->first())
        ->created_at->toStartWith(now()->format(TestCase::DATETIME_FORMAT))
        ->updated_at->toStartWith(now()->format(TestCase::DATETIME_FORMAT));
});

test('When inserting entity managed columns are set on the object', function () {
    $user = new User();
    $user->name = 'Name';
    UserPersistence::insert($user);
    expect($user)
        ->createdAt->toBeInstanceOf(CarbonImmutable::class)
        ->updatedAt->toBeInstanceOf(CarbonImmutable::class);
});

test('Soft-delete columns cannot be overridden', function () {
    $user = new User();
    $user->name = 'Name';
    $user->deletedAt = CarbonImmutable::parse('2023-01-01 12:00');
    UserPersistence::insert($user);
    expect(DB::table('users')->first())
        ->deleted_at->toBeNull();
});

test('When inserting entity soft-delete columns are set to null on the object', function () {
    $user = new User();
    $user->name = 'Name';
    UserPersistence::insert($user);
    expect($user)
        ->deletedAt->toBeNull();
});

test('Can insert owning relations', function () {
    $author = new User();
    $author->name = 'Author';
    UserPersistence::insert($author);
    $editor = new User();
    $editor->name = 'Editor';
    UserPersistence::insert($editor);

    $post = new Post();
    $post->title = 'Title';
    $post->content = 'Content';
    $post->author = $author;
    $post->editor = $editor;
    $post->number = BackedEnum::ONE;

    PostPersistence::insert($post);

    expect(DB::table('posts')->first())
        ->author->toBe($author->getIdentifier())
        ->editor->toBe($editor->getIdentifier());
});

test('Must set owning relation', function () {
    $post = new Post();
    $post->title = 'Title';
    $post->content = 'Content';
    $post->number = BackedEnum::ONE;

    expect(fn() => PostPersistence::insert($post))->toThrow(
        PersistenceException::class,
        'Must set all non-nullable owning relations.'
    );
});

test('Must set ID of owning relation', function () {
    $post = new Post();
    $post->title = 'Title';
    $post->content = 'Content';
    $post->number = BackedEnum::ONE;
    $post->author = new User();

    expect(fn() => PostPersistence::insert($post))->toThrow(
        PersistenceException::class,
        'Owned linked entity must have valid ID set.'
    );
});

test('Can set nullable owning relation to null', function () {
    $user = new User();
    $user->name = 'Name';
    UserPersistence::insert($user);

    $post = new Post();
    $post->title = 'Title';
    $post->content = 'Content';
    $post->number = BackedEnum::ONE;
    $post->author = $user;
    $post->editor = null;

    PostPersistence::insert($post);

    expect(DB::table('posts')->first()->editor)->toBeNull();
});
