<?php

use AdventureTech\ORM\Exceptions\BadlyConfiguredPersistenceManagerException;
use AdventureTech\ORM\Exceptions\IdSetForInsertException;
use AdventureTech\ORM\Exceptions\InvalidEntityTypeException;
use AdventureTech\ORM\Exceptions\MissingIdValueException;
use AdventureTech\ORM\Exceptions\MissingOwningRelationException;
use AdventureTech\ORM\Exceptions\MissingValueForColumnException;
use AdventureTech\ORM\Persistence\PersistenceManager;
use AdventureTech\ORM\Tests\TestCase;
use AdventureTech\ORM\Tests\TestClasses\BackedEnum;
use AdventureTech\ORM\Tests\TestClasses\Entities\Account;
use AdventureTech\ORM\Tests\TestClasses\Entities\Note;
use AdventureTech\ORM\Tests\TestClasses\Entities\Post;
use AdventureTech\ORM\Tests\TestClasses\Entities\User;
use AdventureTech\ORM\Tests\TestClasses\Persistence\AccountPersistence;
use AdventureTech\ORM\Tests\TestClasses\Persistence\NotePersistence;
use AdventureTech\ORM\Tests\TestClasses\Persistence\PostPersistence;
use AdventureTech\ORM\Tests\TestClasses\Persistence\UserPersistence;
use Carbon\CarbonImmutable;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

test('Cannot use base persistence manager to insert entities', function () {
    $user = new User();
    expect(fn() => PersistenceManager::insert($user))->toThrow(
        BadlyConfiguredPersistenceManagerException::class,
        'Need to set $entity when extending'
    );
});

test('Cannot insert non-matching entity', function () {
    $user = new User();
    expect(fn() => PostPersistence::insert($user))->toThrow(
        InvalidEntityTypeException::class,
        'Invalid entity type used in persistence manager'
    );
});

test('Can insert entity', function () {
    $user = new User();
    $user->name = 'Name';
    UserPersistence::insert($user);
    expect(DB::table('users')->get())
        ->toHaveCount(1)
        ->first()->name->toBe('Name');
});

test('When inserting entity the id is set on the object', function () {
    $user = new User();
    $user->name = 'Name';
    UserPersistence::insert($user);
    expect($user->getIdentifier())->toBeNumeric();
});

test('Trying to insert entity with ID already set leads exception', function () {
    $user = new User();
    $user->setIdentifier(1);
    $user->name = 'Name';
    expect(fn() => UserPersistence::insert($user))->toThrow(
        IdSetForInsertException::class,
        'Must not set ID column for insert'
    );
});

test('Trying to insert entity with missing column leads exception', function () {
    $user = new User();
    expect(fn() => UserPersistence::insert($user))->toThrow(
        MissingValueForColumnException::class,
        'Forgot to set non-nullable property "name"'
    );
});

test('ULID is generated when specified on attribute', function () {
    $note = new Note();
    $note->text = 'Should generate ULID';
    NotePersistence::insert($note);

    expect(DB::table('notes')->get())->toHaveCount(1)
        ->and(Str::isUlid($note->id))->toBeTrue();
});

test('Fails if id value is not an ULID if useUlid is true and autogenerated is false', function () {
    $account = new Account();
    $account->id = 1;
    $account->name = 'Should not accept integer as id';
    $account->amount = 50;

    expect(fn () => AccountPersistence::insert($account))->toThrow(
        MissingIdValueException::class,
        'Id column value is missing or is not an ULID'
    );
});

test('Managed columns cannot be overridden', function () {
    $user = new User();
    $user->name = 'Name';
    $user->createdAt = CarbonImmutable::parse('2023-01-01 12:00');
    $user->updatedAt = null;
    UserPersistence::insert($user);
    expect(DB::table('users')->first())
        ->created_at->toStartWith(now()->format(TestCase::DATETIME_FORMAT))
        ->updated_at->toStartWith(now()->format(TestCase::DATETIME_FORMAT));
});

test('When inserting entity managed columns are set on the object', function () {
    $user = new User();
    $user->name = 'Name';
    UserPersistence::insert($user);
    expect($user)
        ->createdAt->toBeInstanceOf(CarbonImmutable::class)
        ->updatedAt->toBeInstanceOf(CarbonImmutable::class);
});

test('Soft-delete columns cannot be overridden', function () {
    $user = new User();
    $user->name = 'Name';
    $user->deletedAt = CarbonImmutable::parse('2023-01-01 12:00');
    UserPersistence::insert($user);
    expect(DB::table('users')->first())
        ->deleted_at->toBeNull();
});

test('When inserting entity soft-delete columns are set to null on the object', function () {
    $user = new User();
    $user->name = 'Name';
    UserPersistence::insert($user);
    expect($user)
        ->deletedAt->toBeNull();
});

test('Can insert owning relations', function () {
    $author = new User();
    $author->name = 'Author';
    UserPersistence::insert($author);
    $editor = new User();
    $editor->name = 'Editor';
    UserPersistence::insert($editor);

    $post = new Post();
    $post->title = 'Title';
    $post->content = 'Content';
    $post->author = $author;
    $post->editor = $editor;
    $post->number = BackedEnum::ONE;

    PostPersistence::insert($post);

    expect(DB::table('posts')->first())
        ->author->toBe($author->getIdentifier())
        ->editor->toBe($editor->getIdentifier());
});

test('Must set owning relation', function () {
    $post = new Post();
    $post->title = 'Title';
    $post->content = 'Content';
    $post->number = BackedEnum::ONE;

    expect(fn() => PostPersistence::insert($post))->toThrow(
        MissingOwningRelationException::class,
        'Must set all non-nullable owning relations'
    );
});

test('Must set ID of owning relation', function () {
    $post = new Post();
    $post->title = 'Title';
    $post->content = 'Content';
    $post->number = BackedEnum::ONE;
    $post->author = new User();

    expect(fn() => PostPersistence::insert($post))->toThrow(
        MissingIdValueException::class,
        'Owned linked entity must have valid ID set'
    );
});

test('Can set nullable owning relation to null', function () {
    $user = new User();
    $user->name = 'Name';
    UserPersistence::insert($user);

    $post = new Post();
    $post->title = 'Title';
    $post->content = 'Content';
    $post->number = BackedEnum::ONE;
    $post->author = $user;
    $post->editor = null;

    PostPersistence::insert($post);

    expect(DB::table('posts')->first()->editor)->toBeNull();
});
